services:
  - type: web
    name: flask-playwright-app
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: gunicorn app:app
